src-00-temp/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Minutes)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <formula>Start_Date_Time__c + (VALUE(TEXT(Duration__c))/1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Group_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Group_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Appointment</label>
    <referenceTo>Group_Appointment__c</referenceTo>
    <relationshipLabel>Group Attendees</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attended on time</fullName>
            </value>
            <value>
                <fullName>Arrived late and seen</fullName>
            </value>
            <value>
                <fullName>Arrived late and not seen</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &gt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Did not attend - no advance warning given</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &gt;24 hours notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Practitioner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Date / Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PCP_Global_Value_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/Group_Appointment__c.object-meta.xml
<CustomObject>
    <label>Group Appointment</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>Group Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Minutes)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Went ahead as scheduled</fullName>
            </value>
            <value>
                <fullName>Went ahead with late start</fullName>
            </value>
            <value>
                <fullName>Group cancelled by service &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Group cancelled by service &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Group cancelled by service &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Group cancelled by service &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Group cancelled by service &gt;24 hours notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Practitioner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Group_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date / Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Planned_Care_Pathway</valueSetName>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Group Appointments</relationshipLabel>
    <relationshipName>Group_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Venue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Venues</relationshipLabel>
    <relationshipName>Venues1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/PCP_Global_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helpline Call</fullName>
    </customValue>
    <customValue>
        <fullName>Management Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Financial</fullName>
    </customValue>
    <customValue>
        <fullName>Mediation</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Skype</fullName>
    </customValue>
    <masterLabel>PCP Global Value Set</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Planned_Care_Pathway.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helpline Call</fullName>
    </customValue>
    <customValue>
        <fullName>Management Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Financial</fullName>
    </customValue>
    <customValue>
        <fullName>Mediation</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Skype</fullName>
    </customValue>
    <masterLabel>Planned Care Pathway</masterLabel>
</GlobalValueSet>

force-app-metadata-removed/main/default/classes/NewGroupAttendeeControllerExtension.cls
public with sharing class NewGroupAttendeeControllerExtension {
    
    private final Id groupId;
    private final Group_Appointment__c currentGroup;
    public List<Case> toSelect {get; set;}
    public List<Appointment__c> existingAppts {get; set;}
    public integer numOfAppts {get;set;}
    public string nameSearchText {get; set;}
    public boolean renderSearchTable {get; set;}
    public id AccountID{get;set;}
    
    public List<Appointment__c> getExisting(){
        return [SELECT Id, Name, Contact__c, Duration__c, Outcome__c, Type__c, Practitioner__c, Start_Date_Time__c, Case__c, Case__r.CaseNumber, Contact__r.Name, Contact__r.Birthdate, Account__r.Name FROM Appointment__c 
                              WHERE Group_Appointment__c = :this.currentGroup.Id AND (Outcome__c = 'Attended on time' OR Outcome__c = 'Arrived late and seen' OR Outcome__c = '')];
    }
    
    public String getStartDateTime(){
        return currentGroup.Start_Date_Time__c.format();
    }
    
    public String getEndDateTime(){
        return currentGroup.End_Date_Time__c.format();
    }
    
    
    public NewGroupAttendeeControllerExtension(ApexPages.StandardController stdController){
        this.groupId = stdController.getId();
        this.currentGroup = [SELECT Id, Name, Start_Date_Time__c, End_date_Time__c, Duration__c, Practitioner__c, Venue__c, Type__c FROM Group_Appointment__C WHERE Id = :groupId];
        this.existingAppts = [SELECT Id, Name, Contact__c, Duration__c, Outcome__c, Type__c, Practitioner__c, Start_Date_Time__c, Case__c, Case__r.CaseNumber, Contact__r.Name, Contact__r.Birthdate, Account__r.Name FROM Appointment__c 
                              WHERE Group_Appointment__c = :this.currentGroup.Id AND (Outcome__c = 'Attended on time' OR Outcome__c = 'Arrived late and seen' OR Outcome__c = '')];
        this.numOfAppts = existingAppts.size();
        this.renderSearchTable = false;
        
    }
    
    public List<SelectOption> getAccountPicklist(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('',''));
        List<Account> accounts = [SELECT Id, Name FROM Account];
        for(Account a : accounts){
            options.add(new SelectOption(a.id, a.name));
        }
        
        return options;
    }
    
    public PageReference attendAll(){
        List<Appointment__c> appts = [SELECT Id, Outcome__c, Name FROM Appointment__c WHERE Group_Appointment__c = :groupId];
        List<Appointment__c> toUpdate = new List<Appointment__c>();
        
        for(Appointment__c a : appts){
            if(a.Outcome__c == null || a.Outcome__c == 'Attended on time'){
            	a.outcome__c = 'Attended on time';
                toUpdate.add(a);
            }else{
                ApexPages.addMessage(new apexPages.Message(ApexPages.Severity.INFO, 'Appointment ' + a.Name + ' could not be marked as attended'));
            }
            
        }
        try{
          	update toUpdate;  
        }catch(exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
        return null;
        
    }
    
    public PageReference caseFromSearch(){
        if(nameSearchText == null || nameSearchText == ''){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No client name entered!'));
        }else if(nameSearchText.length() < 3){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You must enter at least 2 characters into the search box!'));
        }else{
            searchCases();
        }
        return null;
    }
    
    public void searchCases(){
        List<Case> cases = new List<case>();
        string queryText = '%' + nameSearchText + '%';
        system.debug(AccountId);
        Set<Id> caseIds = new Set<Id>();
            for(Appointment__c appt : existingAppts){
                caseIDs.add(appt.Case__c);
            }
        if(this.AccountId == null){
            
            cases = [SELECT ID, CaseNumber, Contact.Name, Contact.Birthdate, Owner.Name, Account.Name FROM Case WHERE 
                     Contact.Name LIKE :queryText AND isClosed = false AND Id NOT IN :caseIds LIMIT 20];
        }else{
            
            cases = [SELECT ID, CaseNumber, Contact.Name, Contact.Birthdate, Owner.Name, Account.Name FROM Case WHERE 
                     Contact.Name LIKE :queryText AND AccountId = :AccountID AND isClosed = false AND ID NOT IN :caseIds LIMIT 20];
        }
        this.toSelect = cases;
		this.renderSearchTable = true;        
    }
    
    public PageReference createAppt(){
        Id CaseId = apexpages.currentPage().getParameters().get('addUserTableCU');
        
        Case c = [SELECT ID, ContactId, Contact.Name FROM Case WHERE Id = :CaseID];
        Appointment__c appt = new Appointment__c(Case__c = c.Id, Venue__c = currentGroup.Venue__c, Practitioner__c = currentGroup.Practitioner__c, Type__c = currentGroup.Type__c, Start_date_Time__c = currentGroup.Start_Date_Time__c, Duration__c = currentGroup.Duration__c, Group_Appointment__c = currentGroup.Id, RecordTypeId = Schema.SObjectType.Appointment__c.getRecordTypeInfosByName().get('Group Appointment').getRecordTypeId());
        try{
            insert(appt);
            system.debug(appt.Name);
            existingAppts.add(appt);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, c.Contact.Name + ' has been successfully added to the group'));
        }catch(Exception ex){
            system.debug('this route');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
      	return null;
        
    }
    
}