src-00-temp/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Minutes)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attended on time</fullName>
            </value>
            <value>
                <fullName>Arrived late and seen</fullName>
            </value>
            <value>
                <fullName>Arrived late and not seen</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &gt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Did not attend - no advance warning given</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &gt;24 hours notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Date / Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Risk__c/Risk__c.object-meta.xml
<CustomObject>
    <label>Risk</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Risk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Risk__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Risk__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Risk__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk__c/fields/Date_Raised__c.field-meta.xml
<CustomField>
    <fullName>Date_Raised__c</fullName>
    <label>Date Raised</label>
    <type>Date</type>
</CustomField>

force-app-metadata-removed/main/default/classes/TakeHelplineCallRiskExtension.cls
public class TakeHelplineCallRiskExtension {
    
    public Appointment__c currentAppt;
    public Risk__c risk {get;set;}
    public Risk__c clRisk {get;set;}
    public Risk__c adRisk {get;set;}
    public Risk__c chRisk {get;set;}
    
    public TakeHelplineCallRiskExtension(ApexPages.StandardController stdController) {
        this.currentAppt = [SELECT ID, Name, Contact__c, Case__c, Account__c, Start_Date_Time__c, Duration__c FROM Appointment__c where ID = :stdController.getID()];
        this.risk = new Risk__c();
        this.clrisk = new Risk__c(Date_Raised__c = Date.today(), Contact__c = currentAppt.Contact__c, RecordTypeID = Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Clinical Risk').getRecordTypeID(), Appointment__c = currentAppt.Id, Case__c = currentAppt.Case__c, Account__c = currentAppt.Account__c);
        this.adrisk = new Risk__c(Date_Raised__c = Date.today(), Contact__c = currentAppt.Contact__c, RecordTypeID = Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Vulnerable Adults').getRecordTypeID(), Appointment__c = currentAppt.Id, Case__c = currentAppt.Case__c, Account__c = currentAppt.Account__c);
        this.chrisk = new Risk__c(Date_Raised__c = Date.today(), Contact__c = currentAppt.Contact__c, RecordTypeID = Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Child Protection').getRecordTypeID(), Appointment__c = currentAppt.Id, Case__c = currentAppt.Case__c, Account__c = currentAppt.Account__c);
    }
    
    public PageReference insertRiskUpdateAppt(){
        if(risk.RecordTypeID == Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Clinical Risk').getRecordTypeId()){
            try{
                insert clRisk;
            }catch(Exception ex){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, ex.getMessage()));
            }
        }else if(risk.RecordTypeID == Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Vulnerable Adults').getRecordTypeId()){
            try{
                insert adrisk;
            }catch(Exception ex){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, ex.getMessage()));
            }
            
        }else if(risk.RecordTypeID == Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Child Protection').getRecordTypeId()){
            try{
                insert chrisk;
            }catch(Exception ex){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, ex.getMessage()));
            }
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, 'You must select a Risk Type!'));
        }
        try{
            Long startDate = currentAppt.Start_Date_Time__c.getTime();
            Long timeNow = DateTime.now().getTime();
            Long minutesBetween = (timeNow - startDate) / 60000;
            minutesBetween = minutesBetween + 3;
            currentAppt.Duration__c = minutesBetween.format();
            currentAppt.Outcome__c = 'Attended on time';
            update currentAppt;
            PageReference retURL = new PageReference('/apex/VerifyAppointmentTime?id=' + currentAppt.Id);
            retURL.setRedirect(true);
              return retURL;
            }
        catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error completing appointment: ' + ex.GetMessage()));
        }
        return null;
        
    }
    
    public List<SelectOption> getRecordTypePicklist(){
        List<SelectOption> selectOptions = new List<SelectOption>();
        selectOptions.add(new SelectOption('-- No Risk Type Selected --', '-- No Risk Type Selected --'));
        selectOptions.add(new SelectOption(Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Clinical Risk').getRecordTypeId(), 'Clinical Risk' ));
        selectOptions.add(new SelectOption(Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Child Protection').getRecordTypeId(), 'Child Protection'));
        selectOptions.add(new SelectOption(Schema.SObjectType.Risk__c.getRecordTypeInfosByName().get('Vulnerable Adults').getRecordTypeId(), 'Vulnerable Adults'));
        return selectOptions;
    } 

}