src-00-temp/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attended on time</fullName>
            </value>
            <value>
                <fullName>Arrived late and seen</fullName>
            </value>
            <value>
                <fullName>Arrived late and not seen</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &gt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Did not attend - no advance warning given</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &gt;24 hours notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Risk__c/Risk__c.object-meta.xml
<CustomObject>
    <label>Risk</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Risk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Risk__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Risk__c/fields/Manager_Sign_Off_at_EOC_Closure__c.field-meta.xml
<CustomField>
    <fullName>Manager_Sign_Off_at_EOC_Closure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Sign Off at EOC Closure</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>This user does not have authority to sign off risk</errorMessage>
        <filterItems>
            <field>$User.Can_Sign_Off_Risk__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Risks3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/classes/CaseClass.cls
/**
 * @File Name          : CaseClass.cls
 * @Description        : 
 * @Author             : Brodie Lawton
 * @Group              : 
 * @Last Modified By   : Brodie Lawton
 * @Last Modified On   : 4/26/2020, 5:21:46 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    4/26/2020   Brodie Lawton     Initial Version
**/
public class CaseClass {
    
    
    public void beforeUpdate(List<Case> cases){
        checkRiskOnCaseClosure(cases);
        checkApptOutcomeOnClosure(cases);
        
    }
    
    public void afterUpdate(List<Case> cases){
        
    }
    
    private void checkRiskOnCaseClosure(List<Case> cases){
        Set<Id> caseIDs = new Set<Id>();
        
        for(Case c: cases){
            if(c.Status == 'Discharged' || c.Status == 'Closed Awaiting Admin'){
                caseIds.add(c.id);
            }
            
        }
        
        List<Risk__c> risks = [SELECT ID, Case__c, Case__r.CaseNumber FROM Risk__c WHERE Case__c in :caseIds AND Manager_Sign_Off_at_EOC_Closure__c = ''];
        
        if(risks.size() > 0){
            for(Case c : cases){
                c.addError('These case(s) cannot be closed as there is outstanding risk');
            }
            
        }
        
        
        
    }
    
    private void checkApptOutcomeOnClosure(List<Case> cases){
        Set<Id> caseIds = new Set<Id>();
        
        for(Case c : cases ){
            if(c.Status == 'Discharged' || c.Status == 'Closed Awaiting Admin'){
                caseIds.add(c.id);
            }
            
        }
        List<Appointment__c> appts = [SELECT ID From Appointment__c WHERE Case__c IN :caseIds AND Outcome__c = ''];
        if(appts.size() > 0){
            for(Case c : cases){
                c.addError('These case(s) cannot be closed as there are appointments without an outcome');
            }
            
        }
        
        
        
        
    }
}