src-00-temp/main/default/objects/Authorisation__c/Authorisation__c.object-meta.xml
<CustomObject>
    <label>Authorisation</label>
    <nameField>
        <displayFormat>AU-{00000}</displayFormat>
        <label>Authorisation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Authorisations</relationshipLabel>
    <relationshipName>Authorisations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/isOpen__c.field-meta.xml
<CustomField>
    <fullName>isOpen__c</fullName>
    <formula>OR(
  TEXT(Status__c)= &apos;Submitted&apos;,
  TEXT(Status__c) = &apos;Initial Approval - Service Manager&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Open?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AuthorisationClass.cls
public class AuthorisationClass {

    private static List<Authorisation__c> toAddError(List<Authorisation__c> approvals){
        Set<Id> caseIds = new Set<Id>();
        
        for(Authorisation__c a : approvals){
            if(a.isOpen__c){
                
                caseIds.add(a.Case__c);
            }
            
        }
        List<Authorisation__c> apps = [SELECT Id, Case__c FROM Authorisation__c WHERE Case__c IN :caseIds AND isOpen__c = true];
        Set<Id> appIds = new Set<Id>();
        for(Authorisation__c a : apps){
            appIds.add(a.Id);
        }
        
        List<Authorisation__c> toReturn = new List<Authorisation__c>();
        for(Authorisation__c a : approvals){
            
            for(Authorisation__c a2 : apps){
                if((a2.Id != a.Id) && (a2.case__c == a.Case__c)){
                    toReturn.add(a);
                }
            }
            
        }
        return toReturn;
        
    }

    public static void addErrors(List<Authorisation__c> approvals){
        for(Authorisation__c a : toAddError(approvals)){
            a.addError('There is already an open approval request against this case!');
        }
    }
    

}