src-03-core-crm/main/default/objects/Account/fields/Core10__c.field-meta.xml
<CustomField>
    <fullName>Core10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Core10</label>
    <type>Checkbox</type>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/GAD_7__c.field-meta.xml
<CustomField>
    <fullName>GAD_7__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GAD-7</label>
    <type>Checkbox</type>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/PHQ_9__c.field-meta.xml
<CustomField>
    <fullName>PHQ_9__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PHQ-9</label>
    <type>Checkbox</type>
</CustomField>

src-00-temp/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Appointment_Notes__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Notes__c</fullName>
    <label>Appointment Notes</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Charge__c.field-meta.xml
<CustomField>
    <fullName>Charge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge</label>
    <referenceTo>Charge__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Minutes)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/No_Template__c.field-meta.xml
<CustomField>
    <fullName>No_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the appointment template will not be populated</description>
    <label>No Template</label>
    <type>Checkbox</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attended on time</fullName>
            </value>
            <value>
                <fullName>Arrived late and seen</fullName>
            </value>
            <value>
                <fullName>Arrived late and not seen</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by or on behalf of client &gt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Did not attend - no advance warning given</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;4 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;8 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;12 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &lt;24 hours notice</fullName>
            </value>
            <value>
                <fullName>Appointment cancelled by service &gt;24 hours notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Practitioner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Date / Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PCP_Global_Value_Set</valueSetName>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/recordTypes/Treatment.recordType-meta.xml
<RecordType>
    <fullName>Treatment</fullName>
    <active>true</active>
    <description>Face to Face / Telephone Appointments</description>
    <label>Treatment</label>
</RecordType>

force-app-metadata-removed/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Charge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <description>Is True when the charge is currently active</description>
    <formula>AND(
TODAY() &gt;= Start_Date__c,
TODAY() &lt;= End_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Is ticked when the charge is currently active</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Questionnaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Questionnaire__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Questionnaires</relationshipLabel>
    <relationshipName>Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Questionnaire__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Questionnaires</relationshipLabel>
    <relationshipName>Questionnaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Questionnaire__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Questionnaires</relationshipLabel>
    <relationshipName>Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/fields/WAW_Complete_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>WAW_Complete_Questionnaire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in TakeHelplineCall VF page to determine between questionnaires that have or haven&apos;t been filled out</description>
    <label>Complete Questionnaire?</label>
    <type>Checkbox</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Questionnaire__c/recordTypes/CORE10.recordType-meta.xml
<RecordType>
    <fullName>CORE10</fullName>
    <active>true</active>
    <label>CORE10</label>
</RecordType>

force-app-metadata-removed/main/default/objects/Questionnaire__c/recordTypes/GAD7.recordType-meta.xml
<RecordType>
    <fullName>GAD7</fullName>
    <active>true</active>
    <label>GAD7</label>
</RecordType>

force-app/main/default/objects/Questionnaire__c/fieldSets/PHQ9.recordType-meta.xml
<RecordType>
    <fullName>PHQ9</fullName>
    <active>true</active>
    <label>PHQ9</label>
</RecordType>

force-app/main/default/globalValueSets/PCP_Global_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helpline Call</fullName>
    </customValue>
    <customValue>
        <fullName>Management Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Financial</fullName>
    </customValue>
    <customValue>
        <fullName>Mediation</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Skype</fullName>
    </customValue>
    <masterLabel>PCP Global Value Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TakeHelplineCallExtension.cls
/**
 * @description       : 
 * @author            : Brodie Lawton
 * @group             : 
 * @last modified on  : 07-16-2020
 * @last modified by  : Brodie Lawton
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   07-13-2020   Brodie Lawton   Initial Version
**/
public class TakeHelplineCallExtension {
    public final Case currentCase;
    public Appointment__c appt {get;set;}
    public Questionnaire__c phq {get;set;}
    public Questionnaire__c gad {get;set;}
    public Questionnaire__c core {get;set;}
    public boolean requiredGAD {get;set;}
    public boolean requiredPHQ {get;set;}
    public boolean requiredCORE {get;set;}
    private boolean isRisk = false;
    private ApexPages.StandardController stdController;
    
    public TakeHelplineCallExtension(ApexPages.StandardController stdController){
        this.currentCase = [SELECT ID, CaseNumber, Referral_Date__c, Account.GAD_7__c, Account.PHQ_9__c, Account.Core10__c FROM Case WHERE ID = :stdController.getId()];
        this.requiredGAD = currentCase.Account.GAD_7__c;
        this.requiredPHQ = currentCase.Account.PHQ_9__c;
        this.requiredCORE = currentCase.Account.CORE10__c;
        Appointment__c appt = new Appointment__c(Case__c = this.currentCase.Id, Start_Date_Time__c = DateTime.now() - (1/1440), Practitioner__c = UserInfo.getUserId(), Type__c = 'Helpline Call', Duration__c = '1', No_Template__c = true);
        appt.Appointment_Notes__c = AppointmentTemplates.assessmentTemplate();

        this.appt = appt;
        
        this.phq = new Questionnaire__c(WAW_Complete_Questionnaire__c = this.requiredPHQ, RecordTypeId = Schema.SObjectType.Questionnaire__c.getRecordTypeInfosByName().get('PHQ9').getRecordTypeId());
        this.gad = new Questionnaire__c(WAW_Complete_Questionnaire__c = this.requiredGAD, RecordTypeId = Schema.SObjectType.Questionnaire__c.getRecordTypeInfosByName().get('GAD7').getRecordTypeId());
        this.core = new Questionnaire__c(WAW_Complete_Questionnaire__c = this.requiredCORE, RecordTypeId = Schema.SObjectType.Questionnaire__c.getRecordTypeInfosByName().get('CORE10').getRecordTypeId());
        this.stdController = stdController;
    }
    
    
    
    public List<SelectOption> getTypePicklist(){
        List<Charge__c> charges = [SELECT Id, Type__c FROM Charge__c WHERE Type__C != 'Helpline Call' AND isActive__c = true AND Account__c = :currentCase.AccountId];
        List<SelectOption> selectOptions = new List<SelectOption>();
        List<String> types = new List<String>();
        
        selectOptions.add(new SelectOption('No Further Treatment Recommended', 'No Further Treatment Recommended'));
        
        for(Charge__c c : charges){
            selectOptions.add(new SelectOption(c.Type__c, c.Type__c)); 
        }
        return selectOptions;
    }   
    
    public PageReference riskTypeInsertAppt(){
        boolean stopInserts = false;
        
        try{
            appt.Id = null;
            insert appt;
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.GetMessage()));
            stopInserts = true;
        }
        try{
            if(stopInserts != true){
                if(gad.WAW_Complete_Questionnaire__c == true){
                    gad.Appointment__c = appt.Id;
                    insert gad;
                }
                
                if(phq.WAW_Complete_Questionnaire__c == true){
                    phq.Appointment__c = appt.Id;
                    insert phq;
                }
                
                if(core.WAW_Complete_Questionnaire__c == true){
                    core.Appointment__c = appt.Id;
                    insert core;
                }
            }
            
            
            
        } catch (Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error creating Questionnaires: ' + ex.GetMessage()));
            stopInserts = true;
        }
        
        try{
            if(stopInserts != true){
                Long startDate = appt.Start_Date_Time__c.getTime();
                Long timeNow = DateTime.now().getTime();
                
                Long minutesBetween = (timeNow - startDate) / 60000;
                minutesBetween = minutesBetween + 3;
                appt.Duration__c = minutesBetween.format();
                
                
                
                update appt;
                
                
              
                PageReference retURL = new PageReference('/apex/TakeHelplineCallRisk?id=' + appt.Id);
                retURL.setRedirect(true);
                return retURL;
                
                
                
            } 
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error completing appointment: ' + ex.GetMessage()));
        }
        return null;
    }   
    
    public PageReference insertRecords(){
      
        boolean stopInserts = false;
        
        try{
            appt.Id = null;
            insert appt;
        }catch(Exception ex){
            stopInserts = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.GetMessage()));
           
        }
        try{
            if(stopInserts != true){
                if(gad.WAW_Complete_Questionnaire__c == true){
                    gad.Appointment__c = appt.Id;
                    try{
                        insert gad;
                    }catch(Exception ex){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error saving GAD7 Questionnaire: ' + ex.getMessage()));
                        delete appt;
                    }
                    
                }
                
                if(phq.WAW_Complete_Questionnaire__c == true){
                    phq.Appointment__c = appt.Id;
                    try{
                        insert phq;
                    }catch(Exception ex){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error saving PHQ9 Questionnaire: ' + ex.getMessage()));
                        delete appt;
                    }
                }
                
                if(core.WAW_Complete_Questionnaire__c == true){
                    core.Appointment__c = appt.Id;
                    try{
                        insert core;
                    }catch(Exception ex){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error saving CORE10 Questionnaire: ' + ex.getMessage()));
                        delete appt;
                    }
                }
            }
            
            
            
        }catch (Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error creating Questionnaires: ' + ex.GetMessage()));
            stopInserts = true;
        }
        
        try{
            if(stopInserts != true){
                Long startDate = appt.Start_Date_Time__c.getTime();
                Long timeNow = DateTime.now().getTime();
                
                Long minutesBetween = (timeNow - startDate) / 60000;
                minutesBetween = minutesBetween + 3;
                appt.Duration__c = minutesBetween.format();
                
                appt.Outcome__c = 'Attended on time';
                
                update appt;
                
                
                isRisk = false;
                PageReference retURL = new PageReference('/apex/VerifyAppointmentTime?id=' + appt.Id);
                retURL.setRedirect(true);
                return retURL;
                
                
                
            } 
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error completing appointment: ' + ex.GetMessage()));
        }
        return null;
        
        
    }
    
    
}