src-03-core-crm/main/default/objects/Account/fields/WAW_Authorisation_Contact__c.field-meta.xml
<CustomField>
    <fullName>WAW_Authorisation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorisation Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Authorisation Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Portal_Authorisation__c.field-meta.xml
<CustomField>
    <fullName>WAW_Portal_Authorisation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Authorisation?</label>
    <type>Checkbox</type>
</CustomField>

src-00-temp/main/default/objects/Authorisation__c/Authorisation__c.object-meta.xml
<CustomObject>
    <label>Authorisation</label>
    <nameField>
        <displayFormat>AU-{00000}</displayFormat>
        <label>Authorisation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/Authorisation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Authorisation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorisation Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contract Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Authorisations</relationshipLabel>
    <relationshipName>Authorisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Authorisation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Authorisations</relationshipLabel>
    <relationshipName>Authorisations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/Contract_Approver_User__c.field-meta.xml
<CustomField>
    <fullName>Contract_Approver_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Approver User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Authorisations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/Contract_Manager__c.field-meta.xml
<CustomField>
    <fullName>Contract_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Authorisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/Date_Time_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Cancelled__c</fullName>
    <label>Date / Time Cancelled</label>
    <type>DateTime</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/Date_Time_Closed__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Closed__c</fullName>
    <label>Date / Time Closed</label>
    <type>DateTime</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/Date_Time_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Opened__c</fullName>
    <label>Date / Time Opened</label>
    <type>DateTime</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Authorisation__c/fields/isOpen__c.field-meta.xml
<CustomField>
    <fullName>isOpen__c</fullName>
    <formula>OR(
  TEXT(Status__c)= &apos;Submitted&apos;,
  TEXT(Status__c) = &apos;Initial Approval - Service Manager&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Open?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Authorisation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Submitted&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Initial Approval - Service Manager</fullName>
            </value>
            <value>
                <fullName>Rejected - Service Manager</fullName>
            </value>
            <value>
                <fullName>Final Approval - Contract</fullName>
            </value>
            <value>
                <fullName>Rejected - Contract</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Authorisation__c/fields/Supporting_Comments__c.field-meta.xml
<CustomField>
    <fullName>Supporting_Comments__c</fullName>
    <label>Supporting Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Case/fields/WAW_Assessment_Recomendation__c.field-meta.xml
<CustomField>
    <fullName>WAW_Assessment_Recomendation__c</fullName>
    <description>The planned care pathway recommended by the therapist upon assessment, populated by process builder</description>
    <label>Assessment Recomendation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/WAW_External_Referrer_Contact__c.field-meta.xml
<CustomField>
    <fullName>WAW_External_Referrer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Bank Workers Charity</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contract Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (External Referrer)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Charge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Additional_Appointment_Authorisation__c.field-meta.xml
<CustomField>
    <fullName>Additional_Appointment_Authorisation__c</fullName>
    <inlineHelpText>Is additional authorisation from the account required?</inlineHelpText>
    <label>Additional Appointment Authorisation?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-00-temp/main/default/classes/authorisationPageExtension.cls
public class authorisationPageExtension {
    
    private final Case currentCase;
    public Account caseAccount {get;set;}
    public Authorisation__c authRecord{get;set;}
    public Authorisation__c authCancel{get;set;}
    public List<String> therapyTypes{get;set;}
    public String typeForInsert{get;set;}
    
    
    public authorisationPageExtension(ApexPages.StandardController controller) {
        this.currentCase = [SELECT ID, Referral_Date__c, CaseNumber, Contact.Name, WAW_External_Referrer_Contact__c, AccountId, WAW_Assessment_Recomendation__c FROM Case WHERE Id = :controller.getId()];
        this.caseAccount = [SELECT ID, OwnerId, WAW_Authorisation_Contact__C, WAW_Portal_Authorisation__c FROM Account WHERE ID = :currentCase.AccountId];
        this.authRecord = new Authorisation__c(Type__c = currentCase.WAW_Assessment_Recomendation__c, Status__c = 'Submitted', Case__c = currentCase.Id, Contract_Manager__c = caseAccount.OwnerId);
        this.authCancel = new Authorisation__c();
        if(currentCase.WAW_External_Referrer_Contact__c != null){
            this.authRecord.Authorisation_Contact__c = currentCase.WAW_External_Referrer_Contact__c;
            
        }else if(caseAccount.WAW_Authorisation_Contact__C != null){
            this.authRecord.Authorisation_Contact__c = caseAccount.WAW_Authorisation_Contact__c;
        }
        else{
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There is no external referrer on this case or on the account. You cannot seek approval without an external approver! Please contact the Service or Administration manager'));
        }
    }
    
    public List<SelectOption> getTypePicklist(){
        List<Charge__c> chargesReqAuthorisation = [SELECT Id, Type__c FROM Charge__c WHERE Additional_Appointment_Authorisation__c = 'Yes' AND Start_Date__c <= :currentCase.Referral_Date__c AND End_Date__c >= :currentCase.Referral_Date__c];
        List<SelectOption> selectOptions = new List<SelectOption>();
        List<String> types = new List<String>();
        
        for(charge__c c : chargesReqAuthorisation){
            types.add(c.Type__c);
        }
        
        if(currentCase.WAW_Assessment_Recomendation__c != null && types.contains(currentCase.WAW_Assessment_Recomendation__c)){
            selectOptions.add(new SelectOption(currentCase.WAW_Assessment_Recomendation__c , currentCase.WAW_Assessment_Recomendation__c));
        }
        for(Charge__c c : chargesReqAuthorisation){
            if(c.Type__c != currentCase.WAW_Assessment_Recomendation__c){
                selectOptions.add(new SelectOption(c.Type__c, c.Type__c));
            }
            
        }
        return selectOptions;
    }   
    
    public Integer getNumOfOpenRequests(){
        return [SELECT Id FROM Authorisation__c WHERE Case__c = :currentCase.Id AND (Status__c = 'Submitted' OR Status__c = 'Initial Approval - Service Manager')].size();
    }
    
    public PageReference insertAuth(){
      
            Id approverUserId = null;
            try{
                approverUserId = [SELECT Id FROM User WHERE ContactID = :authRecord.Authorisation_Contact__c].Id;
            }catch(Exception ex){
                approverUserId = null;
            }
            if(approverUserID != null){
                try{
                    authRecord.Id = null;
                    authRecord.Contract_Approver_User__c = approverUserId;
                    authRecord.Date_Time_Opened__c = DateTime.now();
                    insert authRecord;
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'An authorisation request has been submitted for Case: ' + currentCase.CaseNumber));
                    return new PageReference('/' + authRecord.Id);
                }catch(Exception ex){
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
                    return null;
                }
            }else{
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The approver associated with this client is not a portal user! Contract approvers need to be registered as portal users before they can approve using the portal!'));
                return null;
            }
            
    }
    
    public void cancelApprovalRequest(){
        try{
            Authorisation__c auth = getAuthorisation();
            
            auth.Date_Time_Cancelled__c = DateTime.now();
            auth.Date_Time_Closed__c = DateTime.now();
            auth.Cancellation_Reason__c = authCancel.Cancellation_Reason__c;
            auth.Status__c = 'Cancelled';
            update auth;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Request ' + auth.Name + ' has been successfully cancelled'));
        }catch(Exception ex){
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
    }
    
    public Authorisation__c getAuthorisation(){
        Authorisation__c auth = [SELECT ID, Name, Cancellation_Reason__c, Type__c, Contract_Manager__c, Supporting_Comments__c, Status__c, Case__c, Authorisation_Contact__c, Authorisation_Contact__r.Name, Date_Time_Opened__c, Date_Time_Closed__c FROM Authorisation__c where isOpen__c = true and Case__c = :currentCase.Id LIMIT 1];
        if(auth.id != null){
            return auth;
        }
        else{
            return null;
        }
    }

}