src-03-core-crm/main/default/objects/Account/fields/WAW_Collect_Employee_Information__c.field-meta.xml
<CustomField>
    <fullName>WAW_Collect_Employee_Information__c</fullName>
    <inlineHelpText>Select &apos;Yes&apos; if the contract requires demographics of their employee to be collected when a family member uses the service</inlineHelpText>
    <label>Collect Employee Information?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>WAW_Immediate_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/Group_Appointment__c.object-meta.xml
<CustomObject>
    <label>Group Appointment</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>Group Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Minutes)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Max_Number_of_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Max_Number_of_Attendees__c</fullName>
    <label>Max Number of Attendees</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Practitioner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Group_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date / Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Planned_Care_Pathway</valueSetName>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/Group_Appointment__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Group Appointments</relationshipLabel>
    <relationshipName>Group_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Venue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Venues</relationshipLabel>
    <relationshipName>Venues1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Planned_Care_Pathway.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helpline Call</fullName>
    </customValue>
    <customValue>
        <fullName>Management Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Financial</fullName>
    </customValue>
    <customValue>
        <fullName>Mediation</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Couples Therapy F2F</fullName>
    </customValue>
    <masterLabel>Planned Care Pathway</masterLabel>
</GlobalValueSet>

force-app-metadata-removed/main/default/classes/GroupAppointmentTest.cls
@isTest
public class GroupAppointmentTest {
    
    @isTest public static void overlapTest(){
        Account acct = new Account(name = 'Insight Healthcare', WAW_Collect_Employee_Information__c = null, Industry = 'Other', Phone = '011183839445', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Insight Service').getRecordTypeId());
        insert acct;
        Venue__c v = new Venue__c(name = 'test', Account__c = acct.Id);
        insert v;
        Group_Appointment__c ga = new Group_Appointment__c (Practitioner__c = UserInfo.getUserId(), Type__c = 'Step 3 Counselling Couples Therapy F2F', Start_Date_Time__c = DateTime.now(), Duration__c = '20', Venue__c = v.id, Max_Number_Of_Attendees__c = 5);
        insert ga;
        Group_Appointment__c ga2 = new Group_Appointment__c (Practitioner__c = UserInfo.getUserId(), Type__c = 'Step 3 Counselling Couples Therapy F2F', Start_Date_Time__c = DateTime.now(), Duration__c = '20', Venue__c = v.id, Max_Number_Of_Attendees__c = 5);
        try{
            insert ga2;
        }catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('This appointment overlaps with another active appointment in the practitioners calendar, please check and try again.') ? true : false;
            System.assertEquals(expectedExceptionThrown, true);
        }
    }
}