src-03-core-crm/objects/Account/fields/CCG_Code__c.field-meta.xml
<CustomField>
    <fullName>CCG_Code__c</fullName>
    <description>Unique code for a CCG, available for this record type only</description>
    <externalId>true</externalId>
    <label>CCG Code</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Agreed_Maximum_Annual_Uptake__c.field-meta.xml
<CustomField>
    <fullName>WAW_Agreed_Maximum_Annual_Uptake__c</fullName>
    <label>Agreed Maximum Annual Uptake</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>WAW_Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>6 Monthly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WAW_Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>WAW_Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee Per Service</fullName>
            </value>
            <value>
                <fullName>Periodic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WAW_Capitated_Service_Levels__c.field-meta.xml
<CustomField>
    <fullName>WAW_Capitated_Service_Levels__c</fullName>
    <label>Capitated Service Levels</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>WAW_Contract_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Helpline Plus</fullName>
            </value>
            <value>
                <fullName>Telephone EAP</fullName>
            </value>
            <value>
                <fullName>Full EAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Collect_Employee_Information__c.field-meta.xml
<CustomField>
    <fullName>WAW_Collect_Employee_Information__c</fullName>
    <inlineHelpText>Select &apos;Yes&apos; if the contract requires demographics of their employee to be collected when a family member uses the service</inlineHelpText>
    <label>Collect Employee Information?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>WAW_Immediate_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>WAW_Contract_End_Date__c</fullName>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>WAW_Contract_Start_Date__c</fullName>
    <description>The date the contract with WAW started</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>WAW_Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capitated</fullName>
            </value>
            <value>
                <fullName>Fee For Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WAW_Contracted_Role_of_Call_Taker__c.field-meta.xml
<CustomField>
    <fullName>WAW_Contracted_Role_of_Call_Taker__c</fullName>
    <label>Contracted Role of Call Taker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Specified</fullName>
            </value>
            <value>
                <fullName>Telephone Advisor</fullName>
            </value>
            <value>
                <fullName>Counsellor</fullName>
            </value>
            <value>
                <fullName>Qualified and Experienced Counsellors</fullName>
            </value>
            <value>
                <fullName>Accredited Counsellor</fullName>
            </value>
            <value>
                <fullName>Member of BACP min 5 Years or 500 Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WAW_Employees__c.field-meta.xml
<CustomField>
    <fullName>WAW_Employees__c</fullName>
    <label>Employees?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Helpline_Number__c.field-meta.xml
<CustomField>
    <fullName>WAW_Helpline_Number__c</fullName>
    <label>Helpline Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/WAW_Immediate_Family__c.field-meta.xml
<CustomField>
    <fullName>WAW_Immediate_Family__c</fullName>
    <label>Immediate Family?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WAW_Reporting_Frequency__c.field-meta.xml
<CustomField>
    <fullName>WAW_Reporting_Frequency__c</fullName>
    <label>Reporting Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>6 Monthly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Telephone_Counselling__c.field-meta.xml
<CustomField>
    <fullName>WAW_Telephone_Counselling__c</fullName>
    <label>Telephone Counselling?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-03-core-crm/main/default/objects/Account/recordTypes/CCG.recordType-meta.xml
<RecordType>
    <fullName>CCG</fullName>
    <active>true</active>
    <description>Clinical Commissioning Group</description>
    <label>CCG</label>
</RecordType>

src-00-temp/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Charge__c.field-meta.xml
<CustomField>
    <fullName>Charge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge</label>
    <referenceTo>Charge__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PCP_Global_Value_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/recordTypes/Assessment.recordType-meta.xml
<RecordType>
    <fullName>Assessment</fullName>
    <active>true</active>
    <description>Helpline Calls</description>
    <label>Assessment</label>
</RecordType>

force-app-metadata-removed/main/default/objects/Appointment__c/recordTypes/Treatment.recordType-meta.xml
<RecordType>
    <fullName>Treatment</fullName>
    <active>true</active>
    <description>Face to Face / Telephone Appointments</description>
    <label>Treatment</label>
</RecordType>

force-app-metadata-removed/main/default/objects/CCG__c/CCG__c.object-meta.xml
<CustomObject>
    <label>CCG</label>
    <nameField>
        <label>CCG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CCGs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/CCG__c/fields/CCG_Code__c.field-meta.xml
<CustomField>
    <fullName>CCG_Code__c</fullName>
    <externalId>true</externalId>
    <label>CCG Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app-metadata-removed/main/default/objects/CCG__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Charge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Additional_Appointment_Authorisation__c.field-meta.xml
<CustomField>
    <fullName>Additional_Appointment_Authorisation__c</fullName>
    <inlineHelpText>Is additional authorisation from the account required?</inlineHelpText>
    <label>Additional Appointment Authorisation?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Additional_Session_Fee__c.field-meta.xml
<CustomField>
    <fullName>Additional_Session_Fee__c</fullName>
    <label>Additional Session Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src-07-charge-auth/objects/Charge__c/fields/Charge_Year__c.field-meta.xml
<CustomField>
    <fullName>Charge_Year__c</fullName>
    <label>Charge Period</label>
    <referenceTo>Charge_Year__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge__c/fields/Fee_For_Service_Cost__c.field-meta.xml
<CustomField>
    <fullName>Fee_For_Service_Cost__c</fullName>
    <label>Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge__c/fields/Included_in_Capitated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Included_in_Capitated_Fee__c</fullName>
    <label>Included in Capitated Fee?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-00-temp/main/default/objects/Charge_Year__c/Charge_Year__c.object-meta.xml
<CustomObject>
    <label>Charge Period</label>
    <nameField>
        <displayFormat>CY-{000000}</displayFormat>
        <label>Charge Year Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charge Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-07-charge-auth/objects/Charge_Year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Charge Periods</relationshipLabel>
    <relationshipName>Charge_Years</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge_Year__c/fields/Yearly_Fee__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Fee__c</fullName>
    <inlineHelpText>The managment fee for this period</inlineHelpText>
    <label>Management Fee</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Surgery__c/Surgery__c.object-meta.xml
<CustomObject>
    <label>Surgery</label>
    <nameField>
        <label>Surgery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgeries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Surgery__c/fields/CCG__c.field-meta.xml
<CustomField>
    <fullName>CCG__c</fullName>
    <label>CCG</label>
    <referenceTo>CCG__c</referenceTo>
    <relationshipLabel>Surgeries</relationshipLabel>
    <relationshipName>Surgeries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/PCP_Global_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helpline Call</fullName>
    </customValue>
    <customValue>
        <fullName>Management Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Financial</fullName>
    </customValue>
    <customValue>
        <fullName>Mediation</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Skype</fullName>
    </customValue>
    <masterLabel>PCP Global Value Set</masterLabel>
</GlobalValueSet>

force-app-metadata-removed/main/default/classes/CaseTesting.cls
/**
 * @description       : 
 * @author            : Brodie Lawton
 * @group             : 
 * @last modified on  : 07-13-2020
 * @last modified by  : Brodie Lawton
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   07-13-2020   Brodie Lawton   Initial Version
**/
@isTest
public class CaseTesting {
    private static Case getTestDataNoQuests(){
        Account a = new Account(Name = 'Test Class', industry = 'Healthcare', WAW_Contract_Start_Date__c = Date.newInstance(2020, 03, 03),
            WAW_Contracted_Role_of_Call_Taker__c = 'Telephone Advisor', WAW_Capitated_Service_Levels__c = 'Helpline Plus', WAW_Contract_End_Date__c = Date.newInstance(2021, 03, 03),
            WAW_Contract_Type__c = 'Capitated', WAW_Employees__c = 'Yes', WAW_Immediate_Family__c = 'No', NumberOfEmployees = 200, WAW_Agreed_Maximum_Annual_Uptake__c = 20,
            WAW_Telephone_Counselling__c = 'Yes', WAW_Billing_Type__c = 'Periodic', WAW_Billing_Frequency__c = 'Monthly', WAW_Reporting_Frequency__c = 'Monthly',
            WAW_Helpline_Number__c = '01758447855', WAW_Collect_Employee_Information__c = '');
        insert a;
        Charge_Year__c cp = new Charge_Year__c(Account__c = a.Id, Yearly_Fee__c = 200000, Start_Date__c = Date.newInstance(2020, 03, 03), End_Date__c = Date.newInstance(2021, 03, 03));
        insert cp;
        Charge__c charge = new Charge__c(Account__c = a.Id, Charge_Year__c = cp.Id, Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 0, Additional_Session_Fee__c = 0, Type__c = 'Helpline Call', Included_in_Capitated_Fee__c = 'Yes',
            Start_Date__c = Date.newInstance(2020, 03, 03), End_Date__c = Date.newInstance(2021, 03, 03));
        Charge__c charge2 = new Charge__c(Account__c = a.Id, Charge_Year__c = cp.Id, Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 0, Additional_Session_Fee__c = 0, Type__c = 'Step 3 Counselling Telephone', Included_in_Capitated_Fee__c = 'Yes',
            Start_Date__c = Date.newInstance(2020, 03, 03), End_Date__c = Date.newInstance(2021, 03, 03));
        insert charge;
        insert charge2;
        CCG__c ccg = new CCG__c (name = 'NHS TEST CCG', CCG_Code__c = '22C', Address_Line_1__c = 'CCG Headquaters', Postcode__c = 'TE55 7TT');
        insert ccg;
        Surgery__c s = new Surgery__c (CCG__c = ccg.Id, NHS_Practice_Code__c = 'Test 01');
        insert s;
        Contact contact = new Contact(RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('WAW Client').getRecordTypeId(),AccountId = a.Id, FirstName = 'Test', LastName = 'Class', MobilePhone = '07977531595', Emergency_Info_Declined__c = true, MailingStreet = 'Hill House', MailingCity = 'Test', MailingPostalCode = 'TD4 FFS', Surgery__c = s.Id);
        insert contact;
        Case case1 = new case(RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('WAW Case').getRecordTypeId(), ContactId = contact.Id, AccountId = a.Id, Status = 'New', type = 'Helpline Call', Referral_Date__c = Date.newinstance(2020, 03, 03), Initial_Presenting_Problem__c = 'Addictions - Alcohol', Description = 'Test',
            WAW_Displaying_Risk_on_First_Contact__c = 'No');
        insert case1;
        Test.setCreatedDate(case1.Id, DateTime.NewInstance(2020, 03, 04, 00, 00, 00));
        Appointment__c appt = new Appointment__c(RecordTypeId = Schema.SObjectType.Appointment__c.getRecordTypeInfosByName().get('Assessment').getRecordTypeId(), Case__c = case1.Id, Practitioner__c = UserInfo.getUserId(), Type__c = 'Helpline Call', Outcome__c = 'Attended on time', Start_Date_Time__c = DateTime.newInstance(2020, 05, 05, 12, 00, 00), Duration__c = '5', Assessment_Recomendation__c = 'No Further Treatment Recommended', WAW_Focus_for_Treatment__c = 'test', WAW_Assessment_Risk__c = 'test', WAW_Specific_Client_Information_Needs__c = 'test', WAW_Any_Other_Relevant_Information__c = 'test');
        insert appt;
        return case1;
    }
    @isTest public static void testbeforeUpdate1 (){
        getTestDataNoQuests();
        Case c = [SELECT ID, Status FROM Case LIMIT 1];
        c.status = 'Discharged';
        c.Reason = 'Completed Treatment - with clinical intervention';
        Database.SaveResult srList = Database.update(c, false);

        system.assertEquals(srList.isSuccess(), false);
    }
}