src-03-core-crm/objects/Account/fields/CCG_Code__c.field-meta.xml
<CustomField>
    <fullName>CCG_Code__c</fullName>
    <description>Unique code for a CCG, available for this record type only</description>
    <externalId>true</externalId>
    <label>CCG Code</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Collect_Employee_Information__c.field-meta.xml
<CustomField>
    <fullName>WAW_Collect_Employee_Information__c</fullName>
    <inlineHelpText>Select &apos;Yes&apos; if the contract requires demographics of their employee to be collected when a family member uses the service</inlineHelpText>
    <label>Collect Employee Information?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>WAW_Immediate_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-03-core-crm/main/default/objects/Account/fields/WAW_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>WAW_Contract_Start_Date__c</fullName>
    <description>The date the contract with WAW started</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/WAW_Immediate_Family__c.field-meta.xml
<CustomField>
    <fullName>WAW_Immediate_Family__c</fullName>
    <label>Immediate Family?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-03-core-crm/main/default/objects/Account/recordTypes/CCG.recordType-meta.xml
<RecordType>
    <fullName>CCG</fullName>
    <active>true</active>
    <description>Clinical Commissioning Group</description>
    <label>CCG</label>
</RecordType>

src-03-core-crm/main/default/objects/Account/recordTypes/Surgery.recordType-meta.xml
<RecordType>
    <fullName>Surgery</fullName>
    <active>true</active>
    <label>Surgery</label>
</RecordType>

src-00-temp/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Charge__c.field-meta.xml
<CustomField>
    <fullName>Charge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge</label>
    <referenceTo>Charge__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PCP_Global_Value_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/recordTypes/Assessment.recordType-meta.xml
<RecordType>
    <fullName>Assessment</fullName>
    <active>true</active>
    <description>Helpline Calls</description>
    <label>Assessment</label>
</RecordType>

force-app-metadata-removed/main/default/objects/Appointment__c/recordTypes/Treatment.recordType-meta.xml
<RecordType>
    <fullName>Treatment</fullName>
    <active>true</active>
    <description>Face to Face / Telephone Appointments</description>
    <label>Treatment</label>
</RecordType>

force-app-metadata-removed/main/default/objects/Case/fields/Initial_Presenting_Problem__c.field-meta.xml
<CustomField>
    <fullName>Initial_Presenting_Problem__c</fullName>
    <label>Initial Presenting Problem</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addictions - Alcohol</fullName>
            </value>
            <value>
                <fullName>Addictions - Drug</fullName>
            </value>
            <value>
                <fullName>Addictions - Gambling</fullName>
            </value>
            <value>
                <fullName>Addictions - Internet</fullName>
            </value>
            <value>
                <fullName>Addictions - Other</fullName>
            </value>
            <value>
                <fullName>ADHD</fullName>
            </value>
            <value>
                <fullName>Adoption</fullName>
            </value>
            <value>
                <fullName>Alzheimers</fullName>
            </value>
            <value>
                <fullName>Anger</fullName>
            </value>
            <value>
                <fullName>Anxiety</fullName>
            </value>
            <value>
                <fullName>Anxiety &amp; Depression</fullName>
            </value>
            <value>
                <fullName>Bereavement/Loss</fullName>
            </value>
            <value>
                <fullName>Bipolar disorder</fullName>
            </value>
            <value>
                <fullName>Childhood Issues</fullName>
            </value>
            <value>
                <fullName>Dementia</fullName>
            </value>
            <value>
                <fullName>Depression</fullName>
            </value>
            <value>
                <fullName>Domestic Violence / Abuse</fullName>
            </value>
            <value>
                <fullName>Eating Disorder</fullName>
            </value>
            <value>
                <fullName>Family Difficulties</fullName>
            </value>
            <value>
                <fullName>Gender Condition</fullName>
            </value>
            <value>
                <fullName>Illness/Health Related</fullName>
            </value>
            <value>
                <fullName>Information about Service</fullName>
            </value>
            <value>
                <fullName>Legal and Financial Advice</fullName>
            </value>
            <value>
                <fullName>Long Term Health Condition</fullName>
            </value>
            <value>
                <fullName>Marital</fullName>
            </value>
            <value>
                <fullName>Not disclosed</fullName>
            </value>
            <value>
                <fullName>OCD</fullName>
            </value>
            <value>
                <fullName>Other Benenden Service Required</fullName>
            </value>
            <value>
                <fullName>Phobia</fullName>
            </value>
            <value>
                <fullName>Psychosexual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-metadata-removed/main/default/objects/CCG__c/CCG__c.object-meta.xml
<CustomObject>
    <label>CCG</label>
    <nameField>
        <label>CCG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CCGs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/CCG__c/fields/CCG_Code__c.field-meta.xml
<CustomField>
    <fullName>CCG_Code__c</fullName>
    <externalId>true</externalId>
    <label>CCG Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app-metadata-removed/main/default/objects/CCG__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Charge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Additional_Appointment_Authorisation__c.field-meta.xml
<CustomField>
    <fullName>Additional_Appointment_Authorisation__c</fullName>
    <inlineHelpText>Is additional authorisation from the account required?</inlineHelpText>
    <label>Additional Appointment Authorisation?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Additional_Session_Fee__c.field-meta.xml
<CustomField>
    <fullName>Additional_Session_Fee__c</fullName>
    <label>Additional Session Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src-07-charge-auth/objects/Charge__c/fields/Charge_Year__c.field-meta.xml
<CustomField>
    <fullName>Charge_Year__c</fullName>
    <label>Charge Period</label>
    <referenceTo>Charge_Year__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge__c/fields/Fee_For_Service_Cost__c.field-meta.xml
<CustomField>
    <fullName>Fee_For_Service_Cost__c</fullName>
    <label>Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge__c/fields/Included_in_Capitated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Included_in_Capitated_Fee__c</fullName>
    <label>Included in Capitated Fee?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-00-temp/main/default/objects/Charge_Year__c/Charge_Year__c.object-meta.xml
<CustomObject>
    <label>Charge Period</label>
    <nameField>
        <displayFormat>CY-{000000}</displayFormat>
        <label>Charge Year Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charge Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-07-charge-auth/objects/Charge_Year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Charge Periods</relationshipLabel>
    <relationshipName>Charge_Years</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Charge_Year__c/fields/Yearly_Fee__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Fee__c</fullName>
    <inlineHelpText>The managment fee for this period</inlineHelpText>
    <label>Management Fee</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src-03-core-crm/objects/Contact/fields/Surgery__c.field-meta.xml
<CustomField>
    <fullName>Surgery__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Surgery</label>
    <referenceTo>Surgery__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-metadata-removed/main/default/objects/Risk__c/Risk__c.object-meta.xml
<CustomObject>
    <label>Risk</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Risk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Risk__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk__c/recordTypes/Clinical_Risk.recordType-meta.xml
<RecordType>
    <fullName>Clinical_Risk</fullName>
    <active>true</active>
    <description>Suspected/identified risks relating to self and/or others</description>
    <label>Clinical Risk</label>
</RecordType>

force-app/main/default/objects/Surgery__c/Surgery__c.object-meta.xml
<CustomObject>
    <label>Surgery</label>
    <nameField>
        <label>Surgery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgeries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Surgery__c/fields/CCG__c.field-meta.xml
<CustomField>
    <fullName>CCG__c</fullName>
    <label>CCG</label>
    <referenceTo>CCG__c</referenceTo>
    <relationshipLabel>Surgeries</relationshipLabel>
    <relationshipName>Surgeries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-metadata-removed/main/default/objects/Venue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Venues</relationshipLabel>
    <relationshipName>Venues1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/PCP_Global_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helpline Call</fullName>
    </customValue>
    <customValue>
        <fullName>Management Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Financial</fullName>
    </customValue>
    <customValue>
        <fullName>Mediation</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Book) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 GSH (Computer) Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 2 Support Call Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CBT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 CfD Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Email</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Counselling Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 EMDR Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 IPT Skype</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Face to Face</fullName>
    </customValue>
    <customValue>
        <fullName>Step 3 Mindfulness Skype</fullName>
    </customValue>
    <masterLabel>PCP Global Value Set</masterLabel>
</GlobalValueSet>

force-app-metadata-removed/main/default/classes/TestDataFactory.cls
@isTest 
public class TestDataFactory{
    
    public static integer getRandom(){
        return Math.round((Math.random() * (9000) + 1000));
        
    }    
    
    public static List<Account> createAccounts(integer numAcc, Boolean doInsert) {
        List<Account> accts = new List<Account>();
        for (Integer i = 0; i < numAcc; i++ ){
            //add accounts
            accts.add(new Account(name = 'Test Account ' + Math.round((Math.random() * (9000) + 1000)),
                                  Industry = 'None',
                                  WAW_Immediate_Family__c = 'Yes',
                                  WAW_Collect_Employee_Information__c = 'No', 
                                  WAW_Contract_Start_Date__c = system.today().addYears(-2)));
            
        }
        if(doInsert){
            
            
            insert accts;
            
            
            
        }
        return accts;
    }
    
    public static void insertChargeInfo(Id accountId, Date startDate, Date endDate){
        Charge_Year__c cy = new Charge_Year__c (Account__c = accountId, Yearly_Fee__c = 0, Start_Date__c = startDate, End_Date__c = endDate);
        insert cy;
        Charge__c c1 = new charge__c(Account__c = accountId, Charge_Year__c = cy.Id, Type__c = 'Helpline Call', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = startDate, End_Date__c = endDate, Included_in_Capitated_Fee__c = 'Yes');
        insert c1;
        Charge__c c2 = new charge__c(Account__c = accountId, Charge_Year__c = cy.Id, Type__c = 'Step 2 GSH (Book) Email', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = startDate, End_Date__c = endDate, Included_in_Capitated_Fee__c = 'Yes');
        insert c2;
        Charge__c c3 = new charge__c(Account__c = accountId, Charge_Year__c = cy.Id, Type__c = 'Step 2 GSH (Book) Telephone', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = startDate, End_Date__c = endDate, Included_in_Capitated_Fee__c = 'Yes');
        insert c3;
        system.debug('CHARGES CREATED TEST CLASS LINE 40');
    }
    
    public static List<CCG__c> CreateCCG(Integer numCCG, Boolean doInsert) {
        List<CCG__c> CCGs = new List <CCG__c>();
        //List<Account> accts = createAccounts(1, false);
        //List<Contact> cons = createContact(1, false);
        for(integer i = 0; i < numCCG; i++) {
            CCGs.add(new CCG__c(Name = 'Test CCG ' + i,
                                CCG_Code__c = string.valueOf(getRandom()),
                                Postcode__c = 'NE12 4QQ'));
        }
        if (doInsert){
            insert CCGs;
        }
        return CCGs;
    }
    
    public static List<User> createPractitioner(Integer numUser, Boolean doInsert){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        List<User> users= new List<User>();
        
        users.add(new User(Alias = 'standt', Email='standarduser@testorg.com', 
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com' + Math.round((Math.random() * (9000) + 1000))));
        insert users;
        
        return users;
    }
    
    public static List<Surgery__c> createSurgery(Integer numSurgeries , Boolean doInsert){
        List<Surgery__c> surgeries = new List<Surgery__c>();  
        List<CCG__c> CCGs = createCCG(1, false);
        for (integer i; i < numSurgeries; i++){
            surgeries.add(new Surgery__c(Name = 'test surgery ' + i,
                                         CCG__c = CCGs[i].Id));
        }
        if(doInsert){
            insert surgeries;
        }
        return surgeries;
    } 
    
    public static List<Contact> createContact(integer numContact, Boolean doInsert) {
        List <Contact> cons = new List <Contact>();
        List<Surgery__c> surgeries = createSurgery(1, false);
        List <Account> accts = createAccounts(1, false);
        for (Integer i = 0; i < numContact; i++) {
            cons.add(new Contact(FirstName = 'Test', LastName = 'User ' + i, 
                                 accountid = accts[i].Id, 
                                 surgery__c = surgeries[i].Id
                                ));
        }
        if(doInsert){
            insert cons;
        }
        return cons;
    }
    
    public static List<Case> createCase(Integer numCases, Boolean doInsert) {
        List<Case> Cases = new List <Case>();
        List<Account> accts = createAccounts(1, false);
        List<Contact> cons = createContact(1, false);
        for(integer i = 0; i < numCases; i++) {
            Cases.add(new Case(ContactId = cons[i].Id,
                               AccountId = accts[i].Id,
                               Status = 'New',
                               Type = 'Waiting',
                               Origin = 'Helpline Call',
                               Priority = 'Medium',
                               Initial_Presenting_Problem__c = 'ADHD'
                              ));
        }
        if (doInsert){
            insert Cases;
        }
        return Cases;
    }    
    
    public static List<Appointment__c> createAppointment(integer numAppointments, Boolean doInsert, DateTime appStartDate, String appDuration) {
        
        List<Appointment__c> appointments = new List<Appointment__c>();
        List<Account> accts = createAccounts(1, true);
        List<Contact> cons = createContact(1, true);
        List<Case> cse = createCase(1, true);
        List<User> u = createPractitioner(1, true);
        
        Id RecordTypeIdAppointment = Schema.SObjectType.Appointment__c.getRecordTypeInfosByName().get('Assessment').getRecordTypeId(); 
        for(integer i; i < numAppointments; i++) {
            
            appointments.add(new Appointment__c(RecordTypeId = RecordTypeIdAppointment,
                                                Start_Date_Time__c = appStartDate,
                                                Duration__c = appDuration,
                                                
                                                Account__c = accts[i].Id,
                                                Contact__c = cons[i].Id,
                                                Case__c = cse[i].Id,
                                                Practitioner__c = u[i].Id,
                                                Type__c = 'Helpline Call'
                                               ));
        }
        Set<Id> accountIds = new Set<Id>();
        
        for(Appointment__c a : appointments){
            accountIds.add(a.Account__c);
            
        }
        for(Id accountId : accountIds){
            system.debug('CHARGE TEST CALLED');
            insertChargeInfo(accountId, Date.NewInstance(appStartDate.year(), appStartDate.month(), appStartDate.day()), Date.newInstance(appStartDate.year()+1, appStartDate.month(), appStartDate.Day()));
        }
        if(doInsert) {
            insert appointments;
        }
        return appointments;
    }
    
    
    
    
    
    
    public static List<Appointment__c> createAllAppointmentData(datetime appStartDate, String appDuration){
        
        Account a = new Account(name = 'Test Account ' + Math.round((Math.random() * (9000) + 1000)),                                                                               
                                Industry = 'None',
                                WAW_Immediate_Family__c = 'Yes',
                                WAW_Collect_Employee_Information__c = 'No', 
                                WAW_Contract_Start_Date__c = system.today().addYears(-2));
        insert a;
        
        CCG__c c = new CCG__C(Name = 'Test CCG',
                              CCG_Code__c = string.valueOf(getRandom()),
                              Postcode__c = 'NE12 4QQ');
        insert c;
        
        surgery__c s  = new Surgery__c(Name = 'test surgery',
                                       CCG__c = c.Id,
                                       NHS_Practice_Code__c = string.valueOf(getRandom()));
        
        insert s;
        
        contact con = new contact(FirstName = 'Test',
                                  LastName = 'contact',
                                  AccountId = a.Id,
                                  Surgery__c = s.Id,
                                  Emergency_Info_Declined__c = TRUE);
        
        insert con;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', 
                          Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8',
                          LastName='Testing',
                          LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US',
                          ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', 
                          UserName='standarduser@testorg.com' + Math.round((Math.random() * (9000) + 1000)));
        insert u;
        
        case ca = new case(ContactId = con.Id,
                           AccountId = a.Id,
                           Status = 'New',
                           Type = 'Helpline Call',
                           Origin = 'Helpline Call',
                           Priority = 'Medium',
                           Initial_Presenting_Problem__c = 'ADHD');
        
        insert ca;
        
        /*Id RecordTypeIdRisk= Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Clinical_Risk').getRecordTypeId();

Risk__c rsk = new Risk__c(Account__c = a.Id,
Case__c = ca.Id,
Contact__c = con.Id,
Risk_Rating_Before_Review__c = 'Red',
Risk_Rating_Agreed__c = 'Red',
recordTypeId = RecordTypeIdRisk,
Date_Raised__c = system.today());
insert rsk;*/
        
        Venue__c v = new Venue__c(Name = 'TestVenue',
                                  Account__c = a.Id);
        
        insert v;
        
        Charge_Year__c cy = new Charge_Year__c (Account__c = a.Id, Yearly_Fee__c = 0, Start_Date__c = appStartDate.date(), End_Date__c = appStartDate.date()+10);
        insert cy;
        Charge__c c1 = new charge__c(Account__c = a.Id, Charge_Year__c = cy.Id, Type__c = 'Helpline Call', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = appStartDate.date(), End_Date__c = appStartDate.date()+10, Included_in_Capitated_Fee__c = 'Yes');
        insert c1;
        Charge__c c2 = new charge__c(Account__c = a.Id, Charge_Year__c = cy.Id, Type__c = 'Step 2 GSH (Book) Email', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = appStartDate.date(), End_Date__c = appStartDate.date()+10, Included_in_Capitated_Fee__c = 'Yes');
        insert c2;
        Charge__c c3 = new charge__c(Account__c = a.Id, Charge_Year__c = cy.Id, Type__c = 'Step 2 GSH (Book) Telephone', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = appStartDate.date(), End_Date__c = appStartDate.date()+10, Included_in_Capitated_Fee__c = 'Yes');
        insert c3;
        
        Id AssessmentRT = Schema.SObjectType.Appointment__c.getRecordTypeInfosByDeveloperName().get('Assessment').getRecordTypeId();
        Id F2fRT = Schema.SObjectType.Appointment__c.getRecordTypeInfosByDeveloperName().get('Treatment').getRecordTypeId();
        List<appointment__c> appointments = new List<Appointment__c>();
        appointment__c ap = new appointment__c(Start_Date_Time__c = appStartDate,
                                               Duration__c = appDuration,
                                               Account__c = a.Id,
                                               Contact__c = con.Id,
                                               Case__c = ca.Id,
                                               Practitioner__c = u.Id,
                                               RecordTypeId = AssessmentRT,
                                               Type__c = 'Helpline Call');
        
        
        appointment__c apf2f = new appointment__c(Start_Date_Time__c = appStartDate,
                                                  Duration__c = appDuration,
                                                  Account__c = a.Id,
                                                  Contact__c = con.Id,
                                                  Case__c = ca.Id,
                                                  Practitioner__c = u.Id,
                                                  Venue__c = v.Id,
                                                  RecordTypeId = F2fRT,
                                                  Type__c = 'Step 2 GSH (Book) Email');
        
        appointment__c aptele = new appointment__c(Start_Date_Time__c = appStartDate,
                                                   Duration__c = appDuration,
                                                   Account__c = a.Id,
                                                   Contact__c = con.Id,
                                                   Case__c = ca.Id,
                                                   Practitioner__c = u.Id,
                                                   Venue__c = v.Id,
                                                   RecordTypeId = F2fRT,
                                                   Type__c = 'Step 2 GSH (Book) Telephone');
        appointments.add(ap);
        appointments.add(apf2f);
        appointments.add(aptele);
        
        
        
        insert appointments;
        
        return appointments;
    }         
    
    
    
    public static void createAllAppointmentData(datetime appStartDate, String appDuration, String appType){
        
        Account a = new Account(name = 'Test Account ' + Math.round((Math.random() * (9000) + 1000)),                                                                               
                                Industry = 'None',
                                WAW_Immediate_Family__c = 'Yes',
                                WAW_Collect_Employee_Information__c = 'No', 
                                WAW_Contract_Start_Date__c = system.today().addYears(-2));
        insert a;
		
        Charge_Year__c cy = new Charge_Year__c (Account__c = a.Id, Yearly_Fee__c = 0, Start_Date__c = appStartDate.date(), End_Date__c = appStartDate.date()+10);
        insert cy;
        Charge__c c1 = new charge__c(Account__c = a.Id, Charge_Year__c = cy.Id, Type__c = 'Helpline Call', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = appStartDate.date(), End_Date__c = appStartDate.date()+10, Included_in_Capitated_Fee__c = 'Yes');
        insert c1;
        Charge__c c2 = new charge__c(Account__c = a.Id, Charge_Year__c = cy.Id, Type__c = 'Step 2 GSH (Book) Email', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = appStartDate.date(), End_Date__c = appStartDate.date()+10, Included_in_Capitated_Fee__c = 'Yes');
        insert c2;
        Charge__c c3 = new charge__c(Account__c = a.Id, Charge_Year__c = cy.Id, Type__c = 'Step 2 GSH (Book) Telephone', Additional_Appointment_Authorisation__c = 'No', Fee_For_Service_Cost__c = 25, Additional_Session_Fee__c = 25, Start_Date__c = appStartDate.date(), End_Date__c = appStartDate.date()+10, Included_in_Capitated_Fee__c = 'Yes');
        insert c3;

        CCG__c c = new CCG__C(Name = 'Test CCG',
                              CCG_Code__c = string.valueOf(getRandom()),
                              Postcode__c = 'NE12 4QQ');
        insert c;
        
        surgery__c s  = new Surgery__c(Name = 'test surgery',
                                       CCG__c = c.Id,
                                       NHS_Practice_Code__c = '123456'
                                      );
        
        insert s;
        
        contact con = new contact(FirstName = 'Test',
                                  LastName = 'contact', 
                                  accountid = a.Id, 
                                  surgery__c = s.Id,
                                  Emergency_Info_Declined__c = TRUE);
        
        insert con;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com' + Math.round((Math.random() * (9000) + 1000)));
        insert u;
        
        case ca = new case(ContactId = con.Id,
                           AccountId = a.Id,
                           Status = 'New',
                           Type = 'Waiting',
                           Origin = 'Helpline Call',
                           Priority = 'Medium',
                           Initial_Presenting_Problem__c = 'ADHD'
                          );
        
        insert ca;
        
        appointment__c ap = new appointment__c(Start_Date_Time__c = appStartDate,
                                               Duration__c = appDuration,
                                               Account__c = a.Id,
                                               Contact__c = con.Id,
                                               Case__c = ca.Id,
                                               Practitioner__c = u.Id,
                                               Type__c = apptype);
        insert ap;
        
        /*Id RecordTypeIdRisk= Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Clinical_Risk').getRecordTypeId();

Risk__c rsk = new Risk__c(Account__c = a.Id,
Case__c = ca.Id,
Contact__c = con.Id,
Risk_Rating_Before_Review__c = 'Red',
Risk_Rating_Agreed__c = 'Red',
recordTypeId = RecordTypeIdRisk,
Date_Raised__c = system.today());
insert rsk;*/
    }              
}